### ISSUE TITLE
Datastore Refactoring

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-csharp#4]
Clean up datastore to support:

+ [x] filter chaining
+ [x] abstraction from HTTP objects
+ [x] abstraction from JSON.NET
+ [x] interface to cache manager
+ [x] sync and async paths to RequestExecutor

... more to come

**Comment by nbarbettini** [comment]
Done as of 1c7b1bdfe64069e99cf3dbb60bd94ea7ddb20906
